//go:generate sh -c "cd ../../ && go run plugin_generate.go"
// generated by plugin_generate.go; DO NOT EDIT

package main

import (
	_ "github.com/twxstar/gmqtt/plugin/admin"
	_ "github.com/twxstar/gmqtt/plugin/auth"
	_ "github.com/twxstar/gmqtt/plugin/federation"
	_ "github.com/twxstar/gmqtt/plugin/prometheus"
)
